from time import sleep
name = input("What Is your name?")
sleep (1)
print ("My name is Cindy")
sleep (1)
print ("Nice to meet you " + name + "!")
sleep (1)
age = input("How old are you?")
sleep (1)
print ("I was 28 when they put me in that machine.")
sleep (1)
print ("Wow " + age + " that isnt that old!")
sleep (1)
color = input ("What is your Favorite color")
sleep (1)
print ("Thats is a nice color" + color)
print ("My favorite color was blue before i lost my sight")
sleep (1)
print ("Sorry if I ramble its been so long since i had some one to talk to.")
